CREATE TABLE "mytable" (
  "CREATE DATABASE ProjetoBetConsiente;" text NULL
);

INSERT INTO "mytable" ("CREATE DATABASE ProjetoBetConsiente;")
VALUES
('GO'),
('USE ProjetoBetConsiente;'),
('GO'),
('-- =========================================='),
('-- TABELA DOS USUÁRIOS'),
('-- =========================================='),
('CREATE TABLE Usuarios ('),
('UsuarioID INT IDENTITY (1'),
('ID_Dispositivo VARCHAR(100) NOT NULL UNIQUE'),
('DataCadastro DATETIME DEFAULT GETDATE()'),
('StatusUsuario VARCHAR(20) DEFAULT ''Ativo'''),
(');'),
('GO'),
('-- =========================================='),
('-- TABELA DO HISTÓRICO COMPORTAMENTAL'),
('-- =========================================='),
('-- ---------------------------------------------'),
('-- TABELA CATEGORIA DOS JOGOS'),
('-- ---------------------------------------------'),
('CREATE TABLE CategoriaJogos ('),
('CategoriaID INT IDENTITY (1'),
('NomeCategoria VARCHAR(100) NOT NULL UNIQUE'),
(');'),
('INSERT INTO CategoriaJogos (NomeCategoria) VALUES'),
('(''Slots / Jogos Cash'')'),
('(''Crash '')'),
('(''Aposta Esportivas'')'),
('(''Cassino AO VIVO'') ;'),
('GO'),
(NULL),
('CREATE TABLE HistoricoComportamental ('),
('RegistroID BIGINT IDENTITY (1'),
('UsuarioID INT NOT NULL'),
('DataAcesso DATE NOT NULL'),
('CategoriaID INT NOT NULL'),
('HorarioAcesso TIME NOT NULL'),
('TempoPermanencido INT NOT NULL'),
('CONSTRAINT FK_Historico_Usuarios FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)'),
('CONSTRAINT FK_Historico_Categorias FOREIGN KEY (CategoriaID) REFERENCES CategoriaJogos(CategoriaID)'),
(');'),
('GO'),
('CREATE NONCLUSTERED INDEX IX_HistoricoComportamental_UsuarioID ON HistoricoComportamental(UsuarioID);'),
('CREATE NONCLUSTERED INDEX IX_HistoricoComportamental_CategoriaID ON HistoricoComportamental(CategoriaID);'),
('GO'),
('-- =========================================='),
('-- TABELA DO QUESTIONÁRIO (PGSI)'),
('-- =========================================='),
('CREATE TABLE Questionarios ('),
('AvaliacaoID INT IDENTITY (1'),
('UsuarioID INT NOT NULL'),
('DataResposta DATETIME DEFAULT GETDATE()'),
('PontuacaoTotal INT NOT NULL'),
('ClassificacaoRisco VARCHAR(50) NOT NULL'),
('CONSTRAINT FK_Avaliacoes_Usuarios FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)'),
(');'),
('GO'),
('CREATE NONCLUSTERED INDEX IX_Questionarios_UsuarioID ON Questionarios(UsuarioID);'),
('GO'),
('-- =========================================='),
('-- TABELA DE ALERTAS E ENCAMINHAMENTOS'),
('-- =========================================='),
('CREATE TABLE Alertas ('),
('AlertaID INT IDENTITY (1'),
('UsuarioID INT NOT NULL'),
('DataAlerta DATETIME DEFAULT GETDATE()'),
('TipoAlerta VARCHAR(50) NOT NULL'),
('DirecionamentoRAPS VARCHAR(100) NOT NULL'),
('CONSTRAINT FK_Alertas_Usuarios FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)'),
(');'),
('GO'),
('CREATE NONCLUSTERED INDEX IX_Alertas_UsuarioID ON Alertas(UsuarioID);'),
('GO');
